### ISSUE TITLE
Changelog crashes the document build

### ISSUE THREAD

**Issue by nlopin** [freenowtech/wave#106]
Changelog title applies on every merge and docz cannot build the documentation because there are multiple imports of the same thing in the `changelog.mdx`:

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/1469636/120823270-8fc7e180-c557-11eb-9085-01251439e211.png">

**Comment by nlopin** [comment]
@snapsnapturtle I think you know better how to fix it fast

**Comment by snapsnapturtle** [comment]
I will try to have a look on Monday right away. Unfortunately the documentation of the semantic release notes plugin is a little sparse and there's no way to test the changes beforehand 😞
