### ISSUE TITLE
Add a component to render dropdown of options

### ISSUE THREAD

**Issue by duranmla** [freenowtech/wave#123]
### Describe the feature you'd like

There is already a component developed internally to satisfy this need https://stash.intapps.it/projects/DOPS/repos/react-component-button-dropdown/pull-requests/1/overview and this seems to be a fairly common approach among designers.

### Describe alternatives you've considered

I took a look at the documentation and it seems that we need something similar to https://wave.free-now.com/components/select-list but the trigger is a button instead an input

**Comment by amandaespinosa27** [comment]
I imported to figma the tables files from Abstract. The required button with the floating card can be found in this link.
This button is super important to keep a scalable and yet clean UI to the tables. 
https://www.figma.com/file/o3gNd7JRhey5AdaoIz9pES/freeDS_WAVE-Tables-Import-from-sketch?node-id=0%3A1

**Comment by rafael-sepeda** [comment]
In GAME we use this already
 https://monosnap.com/file/LTzc0SyeQrcJa9vHFincp8sart9RM9
might be that the Automation team already created a component for that. @duranmla You can ask **Inga Schunemann**

**Comment by duranmla** [comment]
Thank you @rafael-sepeda we indeed seems to have different implementations of this already.
_Although, it is sad nobody bring it before to the Design System_

**Comment by martimalek** [comment]
Closing this since the [Popover component](https://wave.free-now.com/?path=/docs/components-popover--docs) can be used for this use case
