### ISSUE TITLE
Tooltip issues on small (mobile) screens

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#13]
Currently the max-width for tooltips is set to 160px, which causes some issues on mobile devices, as seen in the screenshot below. There are currently some ideas on how to fix it
- Allow overriding the max-width, so it's possible to set it to 100% for mobile devices
- Add additional documentation explaining why tooltips should be avoided on mobile devices

<img width="375" alt="Screen Shot 2020-03-05 at 16 05 16" src="https://user-images.githubusercontent.com/8927747/114015691-45cdc280-986a-11eb-8b7b-545110dedff1.png">

**Comment by duranmla** [comment]
What is the preferred solution here?
- Avoid mobile device usage it is feasible? CC: @agonzalezUX @rafael-sepeda 

_If no, then maybe we just add the support for width definiton._

**Comment by agonzalezUX** [comment]
is this tooltip showing up automatically or the user needs to tap on it?

If the user needs to tp on it, I would give a full width with 40px margin left and right

**Comment by snapsnapturtle** [comment]
The user will have to tap on the item the tooltip is connected to (that's the touchscreen way of handling hover events). Let's adjust the tooltip then to use the `max-width: 100%` on the smallest screen size that we support and add the suggested 40px margin.

**Comment by rafael-sepeda** [comment]
@snapsnapturtle From my perspective the issue here is not in the tooltip component but in the copy: it is too long. A tool tip according to guidelines in all design systems is designed for short text helpers. If we need to show such a long message/instruction - we should use a different UI pattern:
- A modal/dialog
- In-line block with instructions.

I can provide a design for this @snapsnapturtle.

**Comment by agonzalezUX** [comment]
I don't know if it make sense to spend time redesigning this tooltip content as the right solution is properly develop the forgot password flow.

**Comment by rafael-sepeda** [comment]
@snapsnapturtle , @agonzalezUX In the PMT in the past we implemented this a bit different - we show a link below that opens a dialog:
https://monosnap.com/file/yVwhWs0HHtRKbUFbdOYfJthydQCaP0

**Comment by snapsnapturtle** [comment]
Thanks for the insights here @rafael-sepeda. Let's keep the tooltip as is and make sure that in the future we are using a different pattern to display large texts. I'll let the dev know who initially reported this :)
