### ISSUE TITLE
Empty state for tables

### ISSUE THREAD

**Issue by chrisrolfe198** [freenowtech/wave#130]
### Describe the feature you'd like
A common empty state for tables (like what currently exists for internal components or some other such item)

### Describe alternatives you've considered
Continue using internal components placeholder or something completely custom.

**Comment by snapsnapturtle** [comment]
@rafael-sepeda @agonzalezUX, do you have some ideas how we can have a shared design for this state or is this unique to each table/project?

**Comment by lloydaf** [comment]
I will close this issue since it doesn't seem relevant right now

**Comment by nlopin** [comment]
We still don't have an empty state for the table, do we?
