### ISSUE TITLE
Crypto api (used by `nanoid`) is missing in some browsers

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#131]
After deploying the Admin Panel with a new version of wave, we noticed an increase of a specific error `ReferenceError: 'crypto' is undefined`. This is very likely caused by the auto-generated ids for inputs (which are using the `nanoid` library). In the library, an error is thrown, when the crypto api does not exist in the browser. I have noticed that in IE 11 the crypto api does not exist.

-   `@freenow/wave` version: 1.4.0 (also applies in the latest version 1.6.0)

### Relevant code

```js

function Example = () => (
    <Input />
);
```

### What was expected to happen?

The component should render normally with a randomly generated id to link the label and the input component.

**Comment by lukahartwig** [comment]
[There is a section on the nanoid README addressing this](https://github.com/ai/nanoid#ie). Should be easy to add this polyfill to the library. Correct me if I'm wrong but I think polyfills count as side effects so we might need to modify the `sideEffects` field in `package.json` as well.
