### ISSUE TITLE
Auto focusing input does not work

### ISSUE THREAD

**Issue by phllipo** [freenowtech/wave#134]
While working on the Admin Panel I wanted to auto focus a wave input and noticed that both the autofocus attribute as well as putting a ref and trying to focus it that way was not working.
When checking it looks like the ref does not actually land on the Input itself, but on the surrounding InputWrapper, which might be the cause. 
Or am I missing something and someone got it to work?

-   `@freenow/wave` version: 1.4.0

### What was expected to happen?

When adding a ref to an Input it lands on the actual input making it possible to auto focus it by using `ref.current.focus()`

**Comment by duranmla** [comment]
Thanks for letting us know @phllipo let's try to reproduce this in an isolated environment before marking it as a bug.
_If you can do it, it would be great. Otherwise, I will do it after we finish with other bugs._

**Comment by snapsnapturtle** [comment]
I've taken the liberty and created a code sandbox https://codesandbox.io/s/wave-playground-forked-kgjsf. As you can see, there's two buttons, one works but has an unexpected usage which should be discouraged and a normal one, which unfortunately doesn't work. It also applies to the latest version of wave (currently 1.8.1).

**Comment by duranmla** [comment]
We are going to tackle this in the next major version ATM I will close this issue in favor of the @snapsnapturtle comment and issue #144
