### ISSUE TITLE
TextButton documentation is missed

### ISSUE THREAD

**Issue by duranmla** [freenowtech/wave#140]
### What was expected to happen?

Going to https://wave.free-now.com/ I am expecting to see `TextButton` but I don't. There is a hint they exist within the Playground at https://wave.free-now.com/components/button

### Reproduction

Go to https://wave.free-now.com/components/button and there is no showcase for TextButton.

**Question.** Shall we create a new page to showcase the `TextButton` or within the same `Button` component page?

**Comment by rafael-sepeda** [comment]
@duranmla Since this is a variation of a button I guess it should be inside the button. Currently there we have a short not at the beginning:
> Renders a button tag. This module exposes two types of buttons <TextButton /> and <Button />

and then an example in the Example block. But probably we could feature all the variants in the "Combinations" block.

@agonzalezUX what do you think?

**Comment by snapsnapturtle** [comment]
I've also herd from a developer in my team that they weren't aware of the text button. I'd suggest we either add a second documentation page (which I would prefer) or add a bigger section to the existing button documentation that explains the difference and has examples for both.

**Comment by rafael-sepeda** [comment]
@snapsnapturtle Good point.
I would be in favour of the second option - adding a bigger section and list all the button types. In most design system there is usually one section for buttons:

- [Orbit](https://orbit.kiwi/components/button/)
- [GitHub’s design system](https://primer.style/css/components/buttons)
- [Material](https://material.io/components/buttons)

**Comment by lloydaf** [comment]
This is already implemented here https://wave.free-now.com/?path=/docs/components-button-textbutton--docs
