### ISSUE TITLE
Accordion Component

### ISSUE THREAD

**Issue by div-Leo** [freenowtech/wave#146]
### Feature: New Accordion component.
Bootstrap reference: [Accordion](https://getbootstrap.com/docs/5.0/components/accordion/)

Following the current implementation in the DMT, we can extract it and add it to Wave.
![vrRqwF4gFR](https://user-images.githubusercontent.com/12762609/124943738-09e2fe80-e00d-11eb-94e6-1d814fee4b3d.gif)

**Comment by rafael-sepeda** [comment]
@div-Leo we will need similar functionality for the **Admin panel** 
cc. @snapsnapturtle 

<img width="1081" alt="Admin+panel+2021-07-09+08-12-22" src="https://user-images.githubusercontent.com/13061805/125032050-b238a780-e08d-11eb-8285-3cb6bdc89fec.png">

**Comment by snapsnapturtle** [comment]
@rafael-sepeda @agonzalezUX can you get us a design that we can implement? :)

**Comment by rafael-sepeda** [comment]
@snapsnapturtle , @div-Leo I will prepare a design for a general Accordion according to what we discussed with @div-Leo last week and get back to you for for feedback.

**Comment by rafael-sepeda** [comment]
I guess we can close this issue because all the work it is done in https://github.com/freenowtech/wave/pull/172
