### ISSUE TITLE
useOffcanvasDismiss is not exported

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#166]
Using the `useOffcanvasDismiss` which is described in the documentation on the Offcanvas page is not exported and can therefore not be used.

-   `@freenow/wave` version: 1.13.2

### Relevant code

```js
import { useOffcanvasDismiss } from '@freenow/wave';

const offcanvasDismiss = useOffcanvasDismiss();
```

### What was expected to happen?

I expect that the functions and components of the library are exported, so they can be used in a project

### Reproduction
https://codesandbox.io/s/wave-playground-forked-0ymjd

**Comment by martimalek** [comment]
Solved in #430
