### ISSUE TITLE
Accordion shows unwanted dividers when expanded

### ISSUE THREAD

**Issue by martimalek** [freenowtech/wave#186]
-   `@freenow/wave` version: 1.16.0

### Relevant code

There is a `<HorizontalDividerTop />` in [line 39 of Accordion.tsx](https://github.com/freenowtech/wave/blob/3f561d00ea9ee82cd37f1c20ecb941a2b91a0e3f/src/components/Accordion/Accordion.tsx#L39) and a `<HorizontalDividerBottom />`
in [line 63 of Accordion.tsx](https://github.com/freenowtech/wave/blob/3f561d00ea9ee82cd37f1c20ecb941a2b91a0e3f/src/components/Accordion/Accordion.tsx#L63)
### What was expected to happen?

The two dividers should not render when the default component is expanded

### Reproduction

You can see the current behaviour in [Wave's accordion page](https://wave.free-now.com/components/accordion)

<img width="985" alt="Screenshot 2021-10-25 at 14 08 41" src="https://user-images.githubusercontent.com/46452321/138692329-923cf41d-2971-4a83-9c5c-3906686591e5.png">

[Link to Figma](https://www.figma.com/file/dTefUItBx5bfbxcCcMzMXm/Wave-DS?node-id=1973%3A67543)

**Comment by lloydaf** [comment]
@martimalek What two dividers should not be expected to be rendered here? The one in the middle should be there?

**Comment by martimalek** [comment]
@lloydaf Yes, the one in the middle should be there, the other two should not

**Comment by arturmiglio** [comment]
Moved to internal backlog.
