### ISSUE TITLE
SelectList | Custom props not getting set

### ISSUE THREAD

**Issue by lloydaf** [freenowtech/wave#194]
-   `@freenow/wave` version:1.16.2

### Relevant code

```jsx
<SelectList
    data-id='bulk_action_select_box'
/>
```

### What was expected to happen?
The `data-id` property should be set on the wrapper/div(s). Properties like `id` work _(because it's explicitly being set)_.

The intention is to be able to set custom properties _(in this case it's for GTM)_ for `SelectList`. Since we're not passing `{...restProps}` to `Wrapper`, it's not being set.

**Comment by lloydaf** [comment]
I was working around this by using the `id` property instead, so it looks like this could still be a valid bug

**Comment by arturmiglio** [comment]
We checked this in the sandbox using v2, and we can use the generated unique id, in cases where a11y selectors are not available.

More info: https://github.com/freenowtech/wave/blob/0029eff111c2db3c78f7e207275903c7f695a6cf/src/components/SelectList/SelectList.tsx#L338
