### ISSUE TITLE
Pagination can display the page size and select a different one

### ISSUE THREAD

**Issue by martimalek** [freenowtech/wave#199]
### Describe the feature you'd like

I'd like the `Pagination` component to optionally display the **page size** and allow to change this value selecting it from a given set of values.

In order to select the wanted page size a `SelectList` would be used:
<img width="916" alt="Screenshot 2022-01-21 at 13 43 42" src="https://user-images.githubusercontent.com/46452321/150529027-48f34895-4562-4586-9580-e9198d844501.png">

**Reasoning**

The reason why I created this issue is because in GAME we want to allow our users to select how many quests they want to see in the quest list from a given set. The `Pagination` is being used there but it currently lacks this feature.

**New API**
I'd add the following props
```jsx
interface PaginationProps {
    /**
     * Page sizes to choose from.
     */
    pageSizes?: {label: string, value: string}[];
    /**
     * Callback when a different page size was selected. Can only be used when `pageSizes` is passed.
     */
    onSelectPageSize?: (selected: { label: string, value: string }) => void;
    ...
}
```

**Comment by lloydaf** [comment]
Sounds like a good idea! I would like to know what the usecase/urgency is though, are there instances where the user needs to change the page sizes?

While this is a nice to have, what I personally struggle with more is switching to the appropriate page. If there was an input box that we can type the name of the page we would like to go to in, I feel like that would solve some of my frustrations 😅 but yeah maybe that's for another issue :)

**Comment by martimalek** [comment]
I've added the reasoning behind the issue on the description, I'd say it's quite urgent since it's something that we expect to have by the end of this week / beginning of the next one. I've started working on it already. 

About switching to the appropriate page I think we'd need design input, maybe @rafael-sepeda could help us out here.

**Comment by rafael-sepeda** [comment]
@lloydaf to be able to jump to a specific page we need to enlarge the `Pagination` component and add pages into it. We can do that in addition. I can prepare a draft/design for this as well. But this might be done in a separate story.

@martimalek since you decided to create a component for Wave for this pattern I will document this a bit better.

**Comment by martimalek** [comment]
@rafael-sepeda I will extend the current `Pagination` but without creating a separate component, not sure if that's what you meant.

**Comment by martimalek** [comment]
After further pondering on the API I'm thinking that maybe `showPageSize` is not a good name for the prop that regulates if the `SelectList` on the left with page sizes will be displayed or not, since the actual page size will be displayed no matter what below the buttons to change page.

Now I'm thinking that maybe just passing `pageSizes` is enough to control whether to show the `SelectList` or not as long as it is well documented in the prop description. I'd like more opinions on this 🙏🏽

**Comment by div-Leo** [comment]
`pageSize` must be passed to the component as `prop` so I don't think it's a good idea. 

But I'm not sure what is the benefit of adding the whole thing to the `Pagination` component. 
Can't it be implemented on the side by implementing a `SelectList` that controls a state for the `pageSize` and pass it to the `Pagination`?

```js
const [pageSize, setPageSize] = useState(PAGE_SIZE)

<>
  <SelectList onChange={setPageSize} options=[10,20,50]/>
  <Pagination pageSize={pageSize}/>
<>
```
This should be possible if I'm not wrong, and I think it's better to control the selector from the outside, instead of adding more concerns to `Pagination`.
But I'm open to changing my mind if you see value in this 😊

**Comment by martimalek** [comment]
@div-Leo Yes it could be used separately. My reasoning behind adding it to Wave was because even though right now only my squad needs it in the future probably _Rider Automation_ and even _Rider Incentives_ may need to implement this.

As for why adding it to the `Pagination` component that's because it's a very small and simple feature for a separate component and it's about changing the number of items for a page, so it would always be used next to `Pagination`.

**Comment by div-Leo** [comment]
It's true that they are bound together as they would handle the interaction with the pages in the table, but in all cases, we'd need to add another external state to pass to the `Pagination` component, which would be the one responsible for the state updates.

I'd need to see the implementation to see what's the trade-off between the gain in terms of saved code and the complexity we add to implement the pagination component.

**Comment by rafael-sepeda** [comment]
@martimalek I added small additional documentation for the PageSize case.
https://www.figma.com/file/dTefUItBx5bfbxcCcMzMXm/Wave-DS?node-id=354%3A22716

let me know if anything is needed in addition.

**Comment by martimalek** [comment]
@rafael-sepeda I think everything is there already, thanks a lot!
