### ISSUE TITLE
Add and change variants for the Label component

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#2]
In order to provide more flexibility and cover more use-cases as a developer/designer I need to have more label-variants. We need to have 5 main types ("variants" now in wave) of labels:
- Default (current Neutral)
- Info (New)
- Success (current Positive)
- Warning (New)
- Danger (current Negative in design and Danger in code)

In addition to our current outlined-style we need to create an additional style-group: *Filled*. Both Outlined and Filled styles need to have 5 label types each. This story also includes the rename of the variant "info" to "neutral".

Design: https://zpl.io/aMWQ1Mr

**Comment by rafael-sepeda** [comment]
@snapsnapturtle Any update on this topic?

**Comment by snapsnapturtle** [comment]
Nothing yet, but I have some changes locally. I can probably open a PR with these and then we have to decide how we want to release them as they will cause a breaking change
