### ISSUE TITLE
Accordion description - replace deprecated prop 'weak' with 'secondary'

### ISSUE THREAD

**Issue by bluessista** [freenowtech/wave#205]
To avoid this deprecation warnings the prop needs to be replaces.
`Warning: [@freenow/wave] 'weak' will be removed in the next major version of Text. Use 'secondary' instead. Rename 'weak' to 'secondary' to remove the warning.`

Appears in the `Accordion` -> `Description` component

**Comment by martimalek** [comment]
It's already resolved in #206
