### ISSUE TITLE
Disabled (read-only) checkboxes are barely visible

### ISSUE THREAD

**Issue by aspasov86** [freenowtech/wave#210]
-   `@freenow/wave` version: 1.13.2

### What was expected to happen?
We have at least AA contrast ratio

### Reproduction
contrast checker results:
https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=FCFCFC

**Comment by rafael-sepeda** [comment]
@aspasov86 yes. [WCAG 2.0 clearly defines that "incidental" text](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) that is not required to meet the contrast requirements. Meaning that disabled text can be barely visible.

**Comment by div-Leo** [comment]
@aspasov86 given @rafael-sepeda comment we're going to close this issue.
