### ISSUE TITLE
New component Popover

### ISSUE THREAD

**Issue by div-Leo** [freenowtech/wave#213]
### Describe the feature you'd like

We need a new component that has the behavior of a Popover. [Here](https://www.figma.com/file/dTefUItBx5bfbxcCcMzMXm/branch/djYaTyPHDwZ8g0MSYWbIcF/Wave-DS?node-id=4119%3A257558) have a draft of the component. It contains also some examples and a possible idea for implementation (to be discussed). 

### Describe alternatives you've considered

Currently, in the DS, we have a Tooltip component that is being used wrongly. We want to have a component that opens next to a target by clicking on it and stays open when we move the cursor.

**Comment by JanHamara** [comment]
Hello everyone, I have one consideration to comment to this from my research on replacement components from Wave for BOMT :)

Component concerned is **ManageBookingDropdown** which still uses the deprecated **@mytaxi/react-component-button-dropdown** and needs a suitable replacement from Wave.

As it is a button element that triggers a dropdown (be it, with some links), I feel like this new Popover component could be an ideal solution for this :) 

Things to consider:
   - are we okay for Popup content to contain links?
   - we would need the Trigger to look exactly like Wave Button + with an icon

**More context**

![Manage Booking Button](https://user-images.githubusercontent.com/14894844/163993499-427672e0-7779-4640-922a-fcb78d5775cb.jpg)

**Comment by rafael-sepeda** [comment]
@JanHamara we have simmilar use cases in **GAME** and **Admin panel** : a button that shows a context menu

**Comment by div-Leo** [comment]
@JanHamara, yes that would be a possible usage. I think the idea is to have flexible content/triggers. 
As @rafael-sepeda mentioned we have already a couple of examples to give a better idea of the possible use cases, see also BulkActions in DMT.
