### ISSUE TITLE
New component: Divider

### ISSUE THREAD

**Issue by JanHamara** [freenowtech/wave#218]
### Describe the feature you'd like
A number of our tools that use Wave DS, including BOMT, DMT, PMT (and possibly more) have many instances of a horizontal or vertical line separating pieces of content. It is being redefined over and over, sometimes as border, sometimes as a div element, despite the fact that its definition is (almost) always identical: 
- **1 pixel width**
- **solid** border
- **color**: AUTHENTIC_BLUE_200 = '#C6CDD4', or in semantic colors **$border.primary**

---

_Examples_

**Navigation Bar (DMT)**
<img width="486" alt="Screenshot 2022-05-02 at 16 23 49" src="https://user-images.githubusercontent.com/14894844/166250707-c835d964-a95d-43d0-ba37-3a32fde58106.png">

**Advanced Search (DMT)**
<img width="893" alt="Screenshot 2022-05-02 at 16 24 35" src="https://user-images.githubusercontent.com/14894844/166250832-09e9441b-c427-4ab2-ac03-67a0c4d053a1.png">

**Fare Breakdown (BOMT)**
<img width="689" alt="Screenshot 2022-05-02 at 16 26 35" src="https://user-images.githubusercontent.com/14894844/166251180-2ccff6c3-d7f9-462e-a632-f584bb7144e2.png">

---

A **Divider** component is often a core component in design systems, therefore, this issue proposes the addition of new <Divider> component to our Wave design system for these and other use-cases.

---

### Proposed architecture

<img width="552" alt="Screenshot 2022-05-02 at 16 31 02" src="https://user-images.githubusercontent.com/14894844/166251923-56999070-6db7-4710-901b-5298469ee4aa.png">

_Note: Little correction, the color would be retrieved as semanticColor $border.primary not from Colors_

**Comment by div-Leo** [comment]
Thanks, @JanHamara for the proposal. It's a component that is widely used scattered in the different projects so I think we will benefit a lot by adding this. 

I would use the sematic color as you mentioned, and about the spacing, I'd extend the design system props to allow more flexibility and use it like this:
```js
<Divider my={3} />
```

Also, have you considered exporting 2 components as `HorizontalDivider` and `VerticalDivider` to be more semantic?
It would be just an abstraction of `<Divider direction="vertical" />` but I don't see cases where we need a dynamic prop and flip it from vertical to horizontal (maybe we do?) while it's rendered. WDYT?

**Comment by JanHamara** [comment]
@rafael-sepeda yes, so the margins are there for defining the spacing around the Divider, I have kept fixed value first `$Spaces[2]`, but yes this should be set as a prop, we spoke with Leo about this already, we'll make it a styled prop. And that will be passed into margin to define the offset of Divider from both sides.

**Comment by rafael-sepeda** [comment]
@JanHamara ok. But does this means that these are all the `margins` around: `margin-top`, `margin-right`, `margin-bottom`,` margin-left`? if so, I would propose to give a possibility to set them individually. The thing is that in design we use, in general, 3 types of dividers:
- full width: with `margin-top` and `margin-bottom` , and NULL for left/right
- middle: `margin-right` and ` margin-left` are the same, but `margin-top` and `margin-bottom` can be bigger
- inset: ` margin-left` is usually big, `margin-right` is NULL, and `margin-top` / `margin-bottom` can be the same
Material has a good example for all of them https://material.io/components/dividers#usage

**Comment by JanHamara** [comment]
@rafael-sepeda 
Personally, and correct me if you disagree, but I believe it would be best if we don't overcomplicate the component and it's single responsibility is simply to render a divider line, either vertical or horizontal and give it the possibility of being offset from its surrounding elements. 

If the divider line is horizontal then logically it divides elements in a column flow, thus we put top and bottom offset. 
If the divider line is vertical than it divides elements in a row, thus we put left and right offset.

---

If we start getting into variants like below...
<img width="358" alt="Screenshot 2022-05-03 at 17 01 07" src="https://user-images.githubusercontent.com/14894844/166479489-fbce5c3b-60c5-4c04-8f46-c99ba496cc45.png">

...and start defining all these various options as variants, such as **big left margin but no right margin**, or **left and right margin small, and top and bottom margin bigger**, and so on, we can then theoretically keep adding these variants endlessly as they appear in our UI and keep adding them to the Divider and we will end up with who-knows how many variants, while these in my opinion are concerns of layout and not of rendering a divider line...

---

_Let me give an example to try explain what I mean_

<img width="358" alt="Screenshot 2022-05-03 at 17 01 07" src="https://user-images.githubusercontent.com/14894844/166479489-fbce5c3b-60c5-4c04-8f46-c99ba496cc45.png">

In the screenshot above, I can see a case of what you described as **big left margin** and **no right margin**...

In my eyes, each food item is:
- container with 2 column layout with elements aligned in a row (let's call this one - **Container A**): first column with image, then column that holds a container with title and paragraph and some sort of ID/order number.
- the container in second column of Container A - let's call it **Container B** - this one has flex-direction: column, correct?
  Inside it, first element is what I will call - **Container C** (flex: row; on the left is heading, on the right is number)
  Next element is the paragraph (we are still in Container B with flex-direction: column)
  And finally the last element should be what I believe the **Divider**, which doesn't have to manage margins to look how it's 
  supposed to look here, it will look like that as a result of being inside the Container B, even with having **width: 100%**.


What I am trying to say here is **why would we define additional CSS margin-left rule inside Divider component to make it look like this, when we can simply achieve the desired UI by placing the divider in the right place? That is, by placing it inside Container B, not inside Container A, which makes us have to manage the Divider's margin to make it look like it's part of the Container B column flow anyways** 

---

I think this applies to other layouts too, in my opinion, the single-responsibility of Divider component should be to render the line with correct orientation and take up full available width (for horizontal) or full available height (for vertical).

Then we can manage various variants with custom margins by wrapping the Divider component in another div, or simply by already having the needed layout (like in the example above).

As you said, for simplicity, I think it would be best to keep it as simple as possible and have devs expect that Divider will always span to full available width/height unless they set up the layout differently. Like for example: https://chakra-ui.com/docs/components/data-display/divider

I'll wait for your thoughts on this 🤔

**Comment by rafael-sepeda** [comment]
@JanHamara yes, I o not want to overcomplicate things. And, as far as I can see in https://chakra-ui.com/docs/components/data-display/divider there is no `margin` property at all. They have `height` and `width`: for a horizontal divider `height` defines the total height of the component (divider + top + bottom), the `width` - the width/length of the line. For a vertical divider, this will do the opposite.

What concerns me is that by setting the margin property we will define (as far I understood you) margin "around" the divider, but in most cases, we need "full width" dividers with zero left/right margins (for horizontal divider) or top/bottom (for vertical).

**Comment by JanHamara** [comment]
@rafael-sepeda yes, I think we are going after same thing actually :) 

Let's try to sum this up, if we're on the same page:

I think Divider should have following behaviour:
 - horizontal divider takes full width by default
 - vertical divider takes full height by default 
  (so that the line, no matter the orientation, spreads fully across the available space in parent container)

If we ever want to somehow change the length of the divider, we wrap it in container that will treat this, it wouldn't be the responsibility of Divider component. This way we have single responsibility: divide two pieces of content with a divider line, and **not** draw a line of custom length..

---

And margin is then used to **offset** the divider **from the surrounding content**.

So, as above in the code, the HorizontalDivider would have (**spacing** here is the prop) following rule: `margin: {spacing} auto` -> we're only setting the top / bottom margin of horizontal line, left and right margin are **auto** so it takes up full width.

The VerticalDivider would have `margin: 0 {spacing}` -> again, we're only setting the left / right margin of vertical line, top and bottom margins are always 0, so it takes up full height.

---

This implementation would also go in line with what you mentioned ''_but in most cases, we need "full width" dividers with zero left/right margins (for horizontal divider) or top/bottom (for vertical)._''

Would you be satisfied with this proposal?

**Comment by rafael-sepeda** [comment]
@JanHamara sounds like a plan!
