### ISSUE TITLE
InlineSpinner in a Button component breaks alignment with other Buttons

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#22]
When placing two `Button` next to each other and using the `InlineSpinner` on one of them, it is breaking the alignment, when the InlineSpinner spins. As the screen record shows, when the first buttons starts the spinner, the second button jumps down and back up when spinning ended.

```
<Button type="submit" mr={2} disabled={state.isLoading || campaignName === ''}>
  {state.isLoading && <InlineSpinner color={Colors.WHITE} />}
  {formatMessage({ id: 'button.createCampaign' })}
</Button>
<Button onClick={handleCampaignLaunch} disabled={isButtonDisabled || isCampaignLaunched} variant={variant}>
  {state.isLoading && <InlineSpinner mr={1} />}
  {children}
</Button>
```

Workaround was to put those Buttons in a `div` with `display: flex;`

https://user-images.githubusercontent.com/8927747/114019141-56803780-986e-11eb-8cf9-f6c6b48dcbc1.mov

**Comment by duranmla** [comment]
@snapsnapturtle as this seems to be a common pattern don't you think we should provide a prop for the spinner to appear? on `loading` let's said.

**Comment by snapsnapturtle** [comment]
I was thinking of providing a prop for adding the spinner as well, but I see a few concerns with this:
- Adding additional items to the button might break layouts that the user of the button might not want
- We could remove the text, but that might also not be expected.

Would be interested in the use cases for how our loading buttons look, but generally speaking I'm in favour of adding a loading state to buttons. It simplifies a lot :)

**Comment by duranmla** [comment]
I added the conversation needed to clarify if we on top of this bug fix we want to add the abstraction for loading buttons.
