### ISSUE TITLE
`TableCell` and `TableHeaderCell` don't apply `display` prop although both accept `LayoutProps`

### ISSUE THREAD

**Issue by arturmiglio** [freenowtech/wave#224]
-   `@freenow/wave` version: [v1.2.0](https://github.com/freenowtech/wave/releases/tag/v1.20.0)

### Relevant code

```js
<TableCell (...) display='none' />
```

Probably missing `layout` in the `compose` function:

https://github.com/freenowtech/wave/blob/517c13628a2b494702704c570e2327ad81421a84/src/components/Table/components/TableCell.tsx#L26
https://github.com/freenowtech/wave/blob/517c13628a2b494702704c570e2327ad81421a84/src/components/Table/components/TableHeaderCell.tsx#L32

### What was expected to happen?

The prop is applied and the display (at least) can be controlled. The main use-case is responsive tables, where we want to hide certain columns to fit narrower screens. Then we could pass responsive to hide elements in certain breakpoints values like:

```js
<TableCell (...) display={['none', 'table-cell']} />
```

And if `display` prop is finally not allowed, typescript should trigger an error.

### Reproduction

https://codesandbox.io/s/wave-playground-forked-bnn69g?file=/src/App.tsx

**Comment by lloydaf** [comment]
So I dug around a bit, and for those who didn't know (I didn't), the display related props don't [exist](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ec6e5981ab3c59704942f53f976cc0150f2feb39/types/react/index.d.ts#L2457) on tr, td elements. I fixed it as per the suggestion in [this](https://github.com/freenowtech/wave/pull/233/commits/eae2cefe7ad554405b67beb9733399fb45c7e9b0) commit but I am not sure that this is the best approach. 

Additionally, should we add layout prop styling for `TableRow` elements as well? probably not related to responsiveness but wondering if there can be usecase to extend this prop to show/hide a row

**Comment by arturmiglio** [comment]
Moved to the internal backlog.
