### ISSUE TITLE
Fix Component Library workflow failing builds on the main branch

### ISSUE THREAD

**Issue by JanHamara** [freenowtech/wave#226]
<img width="990" alt="Screenshot 2022-05-12 at 14 34 51" src="https://user-images.githubusercontent.com/14894844/168075804-c6213db4-652c-4f12-8bd9-2f0866928293.png">

### What it the unexpected behaviour?

For one of our workflows (Component Library) on Wave repo, we are having a build failing on main branch since [this commit](https://github.com/freenowtech/wave/actions/runs/1354323746).

The logs from that commit cannot be found anymore, probably have been deleted after some time based on retention configuration, however, the [latest log](https://github.com/freenowtech/wave/runs/5460958380?check_suite_focus=true) that can be retrieved from one of failing builds shows that it is a merge conflict that’s causing the issue.

### What is the proposed solution?
As per @nlopin we need to manually merge **master** into **next**, resolving the conflicts.

**Comment by martimalek** [comment]
Fixed after [merge next branch into main](https://github.com/freenowtech/wave/actions/runs/7755918003)
