### ISSUE TITLE
Documentation is not accessible via mobile

### ISSUE THREAD

**Issue by arturmiglio** [freenowtech/wave#229]
### What was expected to happen?

Users can't navigate since the link to Github and the hamburger menu are overlapping. Trying to click on the menu, actually triggers the Github link. So it's impossible to navigate.

### Reproduction

To reproduce open the documentation website in a mobile device (tested with a iPhone 8 using Mobile Safari).

![image](https://user-images.githubusercontent.com/539801/169227921-517cc867-2218-42d5-ad1b-79f3a908efd0.jpeg)

There is also a layout issue on the home page: the content of the page is way wider than the hero banner (blue bg):

![image](https://user-images.githubusercontent.com/539801/169227772-9f7086e7-0283-4995-884f-6f014f897915.jpeg)

**Comment by JanHamara** [comment]
Closing the issue, has been resolved.
