### ISSUE TITLE
Switch to React Concurrent Engine (stop supporting react<18)

### ISSUE THREAD

**Issue by nlopin** [freenowtech/wave#239]
As a result of the discussion #212

The new major should rely on the new React Engine. That means we need to change the minimum required version of react in `package.json`.

This also means we can use new React@18 hooks in the library

**Comment by lloydaf** [comment]
We have a lot of tech debt that we need to clean up in BOMT (and maybe even DMT) before we can migrate to react18. I think it's really nice to be able for wave to have react18 support, but dropping support for previous versions is concerning imo, because it wouldn't let older legacy projects to receive updates. Correct me if I misunderstood
@div-Leo @JanHamara do you have any thoughts?

**Comment by nlopin** [comment]
I think we need to create some pressure from the library side of things to move things (DMT and BOMT) forward. It will be easier to justify the refactoring

**Comment by nlopin** [comment]
@lloydaf and @martimalek researched the topic. 

They've changed Wave's required react version to 18 and used a new `useId` hook in the `useGeneratedId` hook. Many essential components use this hook (Input, Textarea, Datepicker, etc.).

After that, they took the oldest project that we have (the DMT) and tried to use this react-18-only library in several scenarios:

- The DMT uses the version of React that we're using now (16.8). The app crashed ❌
- The DMT was promoted to React 18 without switching to the new engine. The app worked with a warning recommending switching to the new engine ✅
- The DMT was promoted to React 18 with the new engine. All good ✅

The learning here is that we can support react 18 only with the new release. This will be a good driver for our applications to migrate to the latest version of react. The migration itself is not complicated, but the migrated app needs validation (manual or e2e)

More info in the [internal issue](https://jira.intapps.it/browse/WECH-21)
