### ISSUE TITLE
Migrate to `useId` from `nanoid` 

### ISSUE THREAD

**Issue by nlopin** [freenowtech/wave#240]
The new React Engine (#239) exposes new [`useId` hook](https://reactjs.org/docs/hooks-reference.html#useid) which can generate stable ids both on the server and frontend side.

That means we can migrate to this hook and remove `nanoid` from the project which solved the same task (not successfully, because ids were not the same on BE and FE sides)

**Comment by martimalek** [comment]
Closing it since it was tackled in #321 and will be merged to `next` with #311
