### ISSUE TITLE
`PhoneInput`: Three symbols phone codes don't fit within width of country select

### ISSUE THREAD

**Issue by vitalybaev** [freenowtech/wave#242]
Phone codes with three symbols are cut because of width of the country select

<img width="370" alt="CleanShot 2022-06-05 at 15 37 31@2x" src="https://user-images.githubusercontent.com/724423/172048741-e4166d64-84e9-480f-a170-316af8ec38ef.png">

-   `@freenow/wave` version: latest I guess, I just opened https://wave.free-now.com/components/phone-input

System: macOS 12.0.1. Browsers: both latest Firefox and Edge.

**Comment by rafael-sepeda** [comment]
I noticed that the DIV that contains the flag and the text has an additional 8px right margin. Probably if we could remove it and use that space for the text this might help. What do you think @nlopin  @martimalek  @div-Leo  ?
![Phone](https://user-images.githubusercontent.com/13061805/172315903-d0d9f560-3c1e-4919-ba00-40a0a80e2254.png)

**Comment by lloydaf** [comment]
<img width="2560" alt="Screenshot 2022-06-09 at 18 02 11 (2)" src="https://user-images.githubusercontent.com/5729666/172892784-373a82f5-2619-48f7-a385-b7adc189e77b.png">
I removed the `max-width` property that was generating this (`8px`), and this is how it currently looks. 
@rafael-sepeda does this look correct with respect to the design specs?

**Comment by rafael-sepeda** [comment]
@lloydaf yes, exactly! This was easy 😅

**Comment by martimalek** [comment]
Closed because of #248
