### ISSUE TITLE
Add tertiary prop to Text

### ISSUE THREAD

**Issue by martimalek** [freenowtech/wave#247]
### Describe the feature you'd like

Currently the `Text` component accepts a `secondary` prop which adjusts it's color to indicate secondary information. 
Since in our semantic colors we already have `text.tertiary` it would make sense to also add a `tertiary` prop to indicate tertiary information.

At the moment the only way to do this would be:

```jsx
export const TertiaryText = styled(Text)`
    color: ${themeGet('semanticColors.text.tertiary')};
`
```

It would be more user friendly to have something like:
```jsx
<Text tertiary>I'm a tertiary text</ Text>
```

### Describe alternatives you've considered

We could also consider deprecating the `secondary` prop to add a `color` (or similar) prop which accepts `secondary | tertiary`
 as value

**Comment by lloydaf** [comment]
Personally I'm in favour of using a generic `color` or `theme` property instead of multiple ones

**Comment by arturmiglio** [comment]
Not relavant anymore
