### ISSUE TITLE
PhoneInput view cut

### ISSUE THREAD

**Issue by dani-walnut** [freenowtech/wave#256]
-   `@freenow/wave` version: 1.25.1

### Relevant code

```js
var your => (code) => here;
```

### What was expected to happen?

After update of the Wave PhoneInput drop down displays cut (currently is not possible to solve via menuPortalTarget as this prop is not being passed)

### Reproduction

Try to register a new driver on https://registration.prelive.free-now.com/ (e.g. Paris - Taxi) on contacts detail page PhoneInput is used.

<img width="528" alt="Screenshot 2022-07-06 at 13 27 00" src="https://user-images.githubusercontent.com/84320593/178911540-2baf8291-3f45-455a-83d9-6eb988819db7.png">

**Comment by nlopin** [comment]
We need to allow to set react portal as a target for the select list

**Comment by lloydaf** [comment]
@dani-walnut can you check the screenshot in the description please? I don't think it's uploaded correctly.

**Comment by dani-walnut** [comment]
fixed
