### ISSUE TITLE
Labels matching semantic colors

### ISSUE THREAD

**Issue by div-Leo** [freenowtech/wave#266]
## Current situation
We have 5 types of labels: 'info' | 'danger' | 'warning' | 'success'  and lastly 'default'
Apart from the last one, we have always the corresponding semantic color (more context 'info'=action blue, 'success'=positive green, 'danger'=negative orange 'warning'=attention yellow) and default uses color secondary

## Proposal 
We should deprecate 'default' (not remove it because it would imply some breaking changes) and use instead 'secondary' as the variant name and add a new one called the 'primary' which will be authentic.

**Comment by arturmiglio** [comment]
I'm a bit confused...

A. Can we use SemanticColors inside components variants definition already?

B. Isn't it `default | info | danger | warning | success` the pattern used for most of the components that expose colour variants? Would those be changing too?

**Comment by div-Leo** [comment]
Update: we decided not to continue with this at the moment. Going to close this issue.
