### ISSUE TITLE
Installing a fresh copy from main branch causes diff on lock file

### ISSUE THREAD

**Issue by arturmiglio** [freenowtech/wave#273]
-   `@freenow/wave` version: Latest

### Relevant code

```js
npm i
```

### What was expected to happen?

No diff is added to package.lock file.

### Reproduction

1. Checkout a new branch;
2. `npm i`;
3. Check package.lock diff;

**Comment by nlopin** [comment]
This is what is supposed to happen because transient dependencies can get new versions, and they can still comply with the package.json of the library that includes them. You should use `npm ci` if you want to use the same dependencies from the package-lock

**Comment by martimalek** [comment]
Closing because of ⬆️ reason
