### ISSUE TITLE
Make Jest the only test runner

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#3]
We have a couple different test kinds which are currently run with a combination of bash scripts and jest. This includes the unit/snapshot tests for all component as well as the e2e fixture tests, but may also be expandable to future tests like visual regression testing. In order to make it easier to include all of these tests in the local development flow we should have a common interface through jest to run these tests with.

With this issue, we want to do the following:
- By default `npm test` should only run the unit tests
- Executing `npm run test:all` should run all tests and is used in CI
- Each jest project can be run individually with an npm script like `npm run test:unit` or `npm run test:screenshot` and so on

What needs to be done:
- Convert fixture tests to jest tests
- Create multi project config for jest
- Create config for unit tests and fixture tests
- Adapt CI script to run all tests concurrently

**Comment by lloydaf** [comment]
@snapsnapturtle should we close #6 if we want to convert them into jest tests? Is there any documentation that exists on how to do this?

**Comment by arturmiglio** [comment]
Moved to internal Backlog
