### ISSUE TITLE
Enhance FilePicker CTA button

### ISSUE THREAD

**Issue by div-Leo** [freenowtech/wave#325]
### Describe the feature you'd like

Allow users to inject a custom component as the CTA button.

ATM we opinionatedly render 2 different CTAs based on desktop/mobile (button for desktop and icon for mobile)
The advantage is to have a more flexible implementation so that the user can choose what to show as CTA.

Mobile FilePicker request:
<img width="304" alt="Screenshot 2023-04-19 at 09 27 52" src="https://user-images.githubusercontent.com/12762609/233000730-63450713-ea81-40cc-bcd1-04aa98d399eb.png">

Questions:
- Do we want to add mobile/desktop components?
- Do we want to add empty/uploaded components?

### Describe alternatives you've considered

We could add another condition to choose whether to force to render the icon or the button in the mobile version.

**Comment by nlopin** [comment]
How do you see this in the API?

**Comment by div-Leo** [comment]
To keep it simple I'd add a single component that replaces any state mobile/desktop and empty/uploaded, and it will look something like this:
```jsx
<FilePicker
  {...}
  ComponentCTA={<TextButton>Add</TextButton>}
/>
```

**Comment by div-Leo** [comment]
Sync outcome: we should push back to keep consistency and avoid component injection. 
Status: stand by

**Comment by arturmiglio** [comment]
Not relevant anymore
