### ISSUE TITLE
Label is missing children type definition

### ISSUE THREAD

**Issue by arturmiglio** [freenowtech/wave#332]
Label props don't include children definition.

### Relevant code

```js
<Label>
    Text
</Label>
```

### What was expected to happen?

No TS error:

`Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes & LabelProps'.`

### Reproduction

https://codesandbox.io/s/elastic-ully-vnv96e

**Comment by rasidre** [comment]
@arturmiglio here is a suggestion to solve this TS message: #340
