### ISSUE TITLE
Error Variant for Tag and SelectList Options

### ISSUE THREAD

**Issue by jahe** [freenowtech/wave#354]
Hello 👋

As part of [RP-10976](https://jira.intapps.it/browse/RP-10976) we would like to add a new variant for "error" state to the [Tag](https://www.figma.com/file/dTefUItBx5bfbxcCcMzMXm/Wave-DS?type=design&node-id=237-7318&mode=design&t=vBRlutCS6iPjIQnL-0) and the [SelectList](https://www.figma.com/file/dTefUItBx5bfbxcCcMzMXm/Wave-DS?type=design&node-id=310-0&mode=design&t=vBRlutCS6iPjIQnL-0) components in wave. The design in figma is [ready](https://www.figma.com/file/dTefUItBx5bfbxcCcMzMXm/Wave-DS?type=design&node-id=237-7318&mode=design&t=vBRlutCS6iPjIQnL-0).

**Proposed Changes**
* Add new prop "variant" to Tag component ([see code](https://github.com/freenowtech/wave/blob/c67d40e939b4a79c91b7a0cef4fe314a2eac59e6/src/components/Tag/Tag.tsx#L11-L11), [see example](https://github.com/freenowtech/wave/blob/c67d40e939b4a79c91b7a0cef4fe314a2eac59e6/lib/types/components/Banner/Banner.d.ts#L7-L7)) and apply the styles accordingly ([see code](https://github.com/freenowtech/wave/blob/c67d40e939b4a79c91b7a0cef4fe314a2eac59e6/src/components/Tag/Tag.tsx#L42-L42))
* Apply custom styles for SelectList option by adjusting StylesConfig ([see code](https://github.com/freenowtech/wave/blob/c67d40e939b4a79c91b7a0cef4fe314a2eac59e6/src/components/SelectList/SelectList.tsx#L137-L137))

**Comment by jahe** [comment]
**Examples**

![image](https://github.com/freenowtech/wave/assets/2736136/495b507d-8c37-4886-b3a1-15fecc1bca5b)
![image](https://github.com/freenowtech/wave/assets/2736136/5ee8f4d4-9eb8-473a-b709-1ec1d7220d7d)

**Comment by nlopin** [comment]
@jahe could you clarify this task a bit? Without the context, It looks like we shouldn't allow the user to select an error option
