### ISSUE TITLE
Add All contributors to our repository 

### ISSUE THREAD

**Issue by duranmla** [freenowtech/wave#36]
We want to acknowledge people that take the time to contribute to the project. To do so we will be integrating https://allcontributors.org/ to our repository.

See the type of contributions we can give at https://allcontributors.org/docs/en/emoji-key
And the usage at https://allcontributors.org/docs/en/bot/usage

**Comment by duranmla** [comment]
@all-contributors please add @nlopin for his excellent work at code doc bug review

**Comment by duranmla** [comment]
Also, we need to add to the other members such as @lukahartwig @snapsnapturtle for the great work at code doc bug and review of pull requests

**Comment by duranmla** [comment]
Also, we need to add to the other members such as @lukahartwig and @snapsnapturtle for the great work at code doc bug and review of pull requests CC: @all-contributors

**Comment by duranmla** [comment]
Also, we need to add to the other members such as @snapsnapturtle for the great work at code doc bug and review of pull requests CC: @all-contributors

**Comment by duranmla** [comment]
It seems to add only one Pull requests to contributors by Issue/PR

**Comment by lukahartwig** [comment]
Nice idea!

**Comment by duranmla** [comment]
I will close this one as it has been tested already. From now on we can add ourselves on PRs 
![image](https://user-images.githubusercontent.com/1425162/115846897-a9d3b780-a422-11eb-932a-6f9771f9d311.png)
