### ISSUE TITLE
Password and Input components require `crossOrigin` prop

### ISSUE THREAD

**Issue by nlopin** [freenowtech/wave#362]
`@freenow/wave` version: latest

### Relevant code

When the `Password` component is used with react types:

"@types/react": "18.2.21",
"@types/react-dom": "18.2.7"

It requires `crossOrigin` property to be set 

### What was expected to happen?

the property is not relevant to inputs, and it shouldn't be required ([mdn](http://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#crossorigin))

### Reproduction

[Code Sandbox](https://codesandbox.io/s/serene-beaver-fn8ds4?file=/src/App.tsx)

**Comment by nlopin** [comment]
UPD: same with the Input

**Comment by martimalek** [comment]
Some info after initial research:
- `crossOrigin` prop is removed from `InputHTMLAttribute` in [this PR of @types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66304)
