### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by duranmla** [freenowtech/wave#39]
My proposition is to unify the way people make PRs by giving a PR template.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

The idea is to state clearly a minimum of things we expect from a PR.

**Comment by duranmla** [comment]
I always like something like:

```
**What:**
Declarative and short sentence of what this PR accomplish
​
**Why:**
A brief explanation over why this need arise and often a link to the ticket
where a further description of the issue/problem can be found.
​
**How:**
Often a list of things to describe the process to accomplish this PR
​
**Media:**
_Optionally._ Depending on the impact of the change or the complexity of the contribution an image or 
a Loom video describing the work made.
```

**Comment by lukahartwig** [comment]
Not sure about this but I think in Github you also have to link the issue that will be solved after the PR is merged, correct?

So that is automatically closes.

If yes, then we should add that to the template as well.

**Comment by duranmla** [comment]
Yes, people need to use `closes`, `fix`, or some keywords to trigger the auto-close.
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
