### ISSUE TITLE
Migrate to Vite

### ISSUE THREAD

**Issue by arturmiglio** [freenowtech/wave#402]
### Describe the feature you'd like

As a Wave contributor, I want to use modern tooling for building Wave

### Describe alternatives you've considered

Manual setup with Rollup, SWC, etc

**Comment by nlopin** [comment]
Hi Artur! We don't bundle the code; the library is shipped as transpiled TS. Hence, we use only the typescript compile to build the library. 

Is there a particular case or situation where Vite is useful? We consider using Vite for storybook, but that's the only use I see.
