### ISSUE TITLE
HSL values in semantic colors table do not match in dark mode

### ISSUE THREAD

**Issue by martimalek** [freenowtech/wave#419]
-   `@freenow/wave` version: 2.x.x

When having the docs in dark mode the hsl values are kept as the same ones for the light mode, which means they don't really match with the actual color displayed

### Relevant code
The bug has to be somewhere near [src/essentials/Colors/docs/SemanticColorsTable.tsx](https://github.com/freenowtech/wave/blob/main/src/essentials/Colors/docs/SemanticColorsTable.tsx)

### Reproduction
<img width="1188" alt="image" src="https://github.com/freenowtech/wave/assets/46452321/5df8b200-30c7-4561-b449-04b35166c7ca">

[See it live here](https://wave.free-now.com/?path=/docs/essentials-colors--docs&globals=theme:classic)

**Comment by nlopin** [comment]
The colours are correct, but the column on the right is statically rendered. We need to change the values there.

I also think we should show both colours, light/dark, at the same time so we see the difference.

**Comment by martimalek** [comment]
> I also think we should show both colours, light/dark, at the same time so we see the difference.

@nlopin I've opened a PR (#420) with the fix for the hsl values but showing both light and dark at the same time is not implemented, I'm not sure if it's needed since the user can change the light/dark scheme at any time to see how a specific color changes, let me know what you think

**Comment by nlopin** [comment]
When I observed Phillip migrating a project to CSS semantic colours, I noticed he hesitated to pick a CSS variable only by semantic name and preferred to check the colours first.

That's why having both colours on the same table would be nice.
