### ISSUE TITLE
Enforced Color Scheme is not applied on Portals

### ISSUE THREAD

**Issue by martimalek** [freenowtech/wave#426]
-   `@freenow/wave` version: 2.x.x

### Relevant code

In `DatepickerSingleInput`, `DatepickerRangeInput` and `Tooltip` we are using [Portals](https://react.dev/reference/react-dom/createPortal) to escape the container element and make sure it doesn't interfere with our components.

These portals will most likely render outside the React root (top level container that you pass to `createRoot(container).render(X)`), in case a color scheme is enforced for the root it won't be applied to the portal.

### What was expected to happen?

Enforced color schemes apply to our components rendered in portals.

### Reproduction

Datepicker container has the light scheme enforced, but the Datepicker appears with dark colors
<img width="461" alt="image" src="https://github.com/freenowtech/wave/assets/46452321/6e9bf8cd-b00c-4562-b3bc-02f823216b2f">

Check it out in [this codesandbox](https://codesandbox.io/p/sandbox/wave-v2-color-scheme-on-portals-3pzkpy)

**Comment by nlopin** [comment]
Great catch!
