### ISSUE TITLE
Add documentation page for designers

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#5]
We already have a page that helps developers and other contributors to improve the design system. We now want to add a new section or page for the design-specific ways to contribute to the design system.

We need to add the following confluence page as a documentation page to the design system, so it's easily accessible by the designers: https://confluence.intapps.it/x/tqSiB.

**Comment by lloydaf** [comment]
https://mytaxi.slack.com/archives/CEE46LAQM/p1659426682706539
Will consider in the future
