### ISSUE TITLE
Contributors list not up to date

### ISSUE THREAD

**Issue by arturmiglio** [freenowtech/wave#53]
There are missing contributors in the README. 

![Github - All contributors screen-shot](https://i.postimg.cc/HLQ9RkbB/github-com-freenowtech-wave.png)

Maybe the @all-contributors bot is not setup?

--

Which brings us to another question: what about past contributors (pre GitHub)?

**Comment by duranmla** [comment]
All contributors it is setup. But it works manually, thus we have the control to what/whom to add it the list.
In this case, it was my mistake for not taking into account the PR you did. 

@all-contributors add @arturmiglio for helping us with the documentation 

Thanks, and apologise for my mistake. Previous contributors hopefully will comeback and keep helping us to move forward as you have done it! Thanks!

**Comment by duranmla** [comment]
@all-contributors add @arturmiglio for helping us with the documentation
