### ISSUE TITLE
Deprecated Input component variant "bottom-lined"

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#7]
As the bottom-lined input components add a lot of development and maintainance and are barely (or not at all used), we decided to drop support starting in version 2 of wave. In this task, we will let the teams know about the deprecation and also mark the component as deprecated in the library.

*Reasoning*
- Exponentially increasing complexity per component that supports bottom lined inputs
- Rarely or not at all used in the tools

*Components to Update*
- Input
- Select
- SelectList
- DateRangePicker
- DatePicker
- PhoneInput

*ToDos*
- Inform the team about the deprecations
- Update the components to show a deprecation warning
- Create a follow-up story to remove the components from the library

**Comment by lloydaf** [comment]
@nlopin should we close this issue in favour of the newer one?

**Comment by lloydaf** [comment]
Closing in favor of the newer one

**Comment by nlopin** [comment]
I consider this as a subtask, but it is fine

**Comment by lloydaf** [comment]
We can reopen it later if we feel the need to have both to separate work more easily, just trying to clean up in the meantime to make issues more maintainable
