### ISSUE TITLE
Performance improvements for PhoneInput

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#8]
When rendering a list of 200+ items showing the flag, name and phone area code, most computers are not able to handle this in an efficient way and clicking on the phone area code selector can take up to a second to show the list of items. We want to improve this, by reducing the time the user has to wait for the list of countries to appear:

* Add react-virtualize/react-window the list to render only visible items
 * Consider loading all the available flags together with the component

**Comment by lukahartwig** [comment]
Likely related to #57
