### ISSUE TITLE
New Password input component

### ISSUE THREAD

**Issue by dani-walnut** [freenowtech/wave#81]
We would like to create a new component for inputting/creating a password. Based on a design we were provided for one of our projects.
![Screenshot 2021-05-17 at 12 42 02](https://user-images.githubusercontent.com/84320593/118476161-73c9e080-b70d-11eb-842e-d8c53936aa7a.png)
![Screenshot 2021-05-17 at 12 42 13](https://user-images.githubusercontent.com/84320593/118476170-79272b00-b70d-11eb-84e0-489a00b8655e.png)

The difference from the already existing <Input /> of a type password is the eye icon which enables user to switch between the visibility of the inputted text.

Technical solution:
We would reuse the existing Input component, with the fixed password type and adding an eye icon which will work as a button switching between input type -> password/text

Options:
1) Create a specific Input type - being included in the Input folder ( + it's kinda a derivate from already existing Input anyway)
2) Create a stand alone component ( + better visibility)

**Comment by snapsnapturtle** [comment]
That's a really good point! Thanks for outlining your two ideas for implementation. Personally I'm tending towards option 2, creating a new component, since this component uses the input _and adds additional functionality_.

**Comment by nlopin** [comment]
I also in favor for the second option, but what I don't like is that a user can still use a regular one via `<Input type="password">...`. Do you see the issue in that?

I don't think it is that harmful, but worth to mention the new component in the documentation of the `Input`

**Comment by nlopin** [comment]
I've recently read [an article from GOV.UK about password component](https://technology.blog.gov.uk/2021/04/19/simple-things-are-complicated-making-a-show-password-option/). We will reuse the knowledge from there

**Comment by lloydaf** [comment]
I am of the opinion that we should favor `<Input type="password" />` over the creation of a separate component, to keep it consistent with `<input type="password" />`. If we want to create a new component, then I would expect to get an error when I try `<Input type="password" />`

**Comment by nlopin** [comment]
We can make them aliases I think

**Comment by dani-walnut** [comment]
Regarding Lloyd's comment - remember it's not only about the pwd type but also about the eye icon functionality which adds a reason for a separate component, in my opinion.

**Comment by lloydaf** [comment]
I like the idea of aliasing. Having a separate component but still being able to access it using `type=password` from the Input component.

**Comment by snapsnapturtle** [comment]
The idea of the input component is to stay relatively close to the native implementation. I'd suggest that we provide a new component with the eye-icon to show/hide the user's input  and call it something like PasswordInput. Additionally we add some documentation to the Input component, letting the users know that there's a component for passwords specifically. If they do not want to use the hide/show functionality, they can fallback to the default one? 

It's a different story, if we want to **only** use the password input with an icon. Then I would suggest we use the alias. Or no new component at all, and just include it with the normal input component but attach this behaviour to the type=password prop. 

@agonzalezUX @rafael-sepeda, do we have any guidelines from design/ux on the password inputs across our apps?

**Comment by duranmla** [comment]
Please let's make sure to evaluate to make the alias. For me makes sense @lloydaf idea and will make easier to enforce all apps to use the same Input password and create this homogeneous experience we want to provide.
