### ISSUE TITLE
The value for shadows.medium is bigger then it should be

### ISSUE THREAD

**Issue by rafael-sepeda** [freenowtech/wave#82]
The values for the shadows in https://github.com/freenowtech/wave/blob/main/src/essentials/theme.ts are:
```
shadows: {
    small: '0 0.0625rem 0.25rem 0 rgba(0,0,0,0.1)',
    medium: '0 0 1rem 0.1875rem rgba(0,0,0,0.08)',
    large: '0 0 0.75rem 0.25rem rgba(0,0,0,0.12)'
}
```
Looks like the `blur-radius` is set wrong for `medium`: it is `1rem`, but it should be `0.5rem`

**Comment by snapsnapturtle** [comment]
@rafael-sepeda thanks for reporting this inconsistency. Can you double check that only the medium shadow is incorrect? (The title of the issue mentions small and the description mentions medium, that's why I'm asking)

**Comment by rafael-sepeda** [comment]
@snapsnapturtle Yes, sorry for confusion. I wanted first to say "small issue" but then wrote the name of the item.

The issues is only with `shadows.medium`
