### ISSUE TITLE
End experimental status for the Table components

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#9]
After collecting feedback and we have the official design documentation for this component, we can remove the experimental warning.

- Detailed documentation for Table is added
- Experimental status is removed

**Comment by lloydaf** [comment]
Is this just a change in documentation? Do we need any code changes?

**Comment by snapsnapturtle** [comment]
Pretty much. We initially created this component as experimental, because we were "experimenting" and verifying if the Table component is usable and works for the teams.
