### ISSUE TITLE
InlineSpinner does not reflect the `size` prop

### ISSUE THREAD

**Issue by nlopin** [freenowtech/wave#95]
Both sizes look the same:

![image](https://user-images.githubusercontent.com/1469636/119808639-9c5b9280-bee4-11eb-9d20-b5be5ac2d730.png)

**Comment by snapsnapturtle** [comment]
For reference: The small size should be `1rem` and the medium size should be `1.25rem` in width & height.

**Comment by snapsnapturtle** [comment]
I noticed another issue with the inline spinner component. Since the change in pr #77, the component accepts no props anymore. This results in the margin and the size props being ignored (breaking builds in ts).
